# Use uma imagem base oficial do Ubuntu
FROM ubuntu:latest

# Definindo variáveis de ambiente para evitar interação manual
ENV DEBIAN_FRONTEND=noninteractive

# Define argumentos de versão para facilitar atualizações do Trivy
ARG TRIVY_VERSION=0.51.1

# Define ponto de inicio para imagem
USER root
WORKDIR /root/

# Atualizações e instalação de pacotes necessários
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    vim \
    curl \
    adduser \
    sudo \
    python3 \
    python3-pip \
    python3-venv \
    ssh \
    net-tools \
    git \
    wget \
    ca-certificates \
    openssh-server \
    openjdk-21-jdk \
    lsb-release \
    software-properties-common \
    apt-transport-https \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Definindo variáveis de ambiente para Java
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Criar o diretório .ssh se não existir
RUN mkdir -p /root/.ssh

# Verificar se as chaves SSH já existem, se não, gerar novas
RUN if [ ! -f /root/.ssh/id_rsa ]; then \
    ssh-keygen -t rsa -b 4096 -f /root/.ssh/id_rsa -N ""; \
    chmod 600 /root/.ssh/id_rsa; \
    chmod 644 /root/.ssh/id_rsa.pub; \
  else \
    echo "Chaves SSH já existem, ignorando a criação de novas."; \
  fi

# Configurações do SSH
RUN mv /etc/ssh/sshd_config /etc/ssh/sshd_config.default
RUN rm -f /root/.ssh/*

# Baixa e instala o Trivy
RUN wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.deb && \
    dpkg -i trivy_${TRIVY_VERSION}_Linux-64bit.deb && \
    rm trivy_${TRIVY_VERSION}_Linux-64bit.deb

# Instalação do Docker CLI
RUN apt-get update && \
    apt-get install -y ca-certificates curl gnupg && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    chmod a+r /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce-cli

# Instalação do Docker Compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

# Cria o grupo Docker e adiciona o usuário root a ele
RUN groupadd docker || true && usermod -aG docker root

# Configura o ponto de entrada para o executável do Trivy
# ENTRYPOINT ["trivy"]

# Por padrão, executa um escaneamento no sistema de arquivos. Isso pode ser substituído na linha de comando.
# Comando sendo executado dentro do docker compose
# CMD ["fs", "/"]

# Diretorio para inicio dos trabalhos
WORKDIR /root/
# Expondo a porta do SSH
EXPOSE 22

# Comando para iniciar o serviço SSH e manter o container em execução
CMD service ssh start && /bin/bash